### ISSUE TITLE
env and run error fix

### ISSUE THREAD

**Issue by zdx3578** [k4ntz/NUDGE#3]

**Comment by k4ntz** [comment]
The python version we have used is 3.8 yes

**Comment by zdx3578** [comment]
pip install torch ocatari

**Comment by zdx3578** [comment]
training environment name : Getout
Set all environment deterministic to seed 0
Traceback (most recent call last):
  File "src/train.py", line 343, in <module>
    main()
  File "src/train.py", line 86, in main
    env = gym.make(args.env, generator_args={"spawn_all_entities": False})
  File "/home/jz/miniconda3/envs/py38/lib/python3.8/site-packages/gym/envs/registration.py", line 569, in make
    _check_version_exists(ns, name, version)
  File "/home/jz/miniconda3/envs/py38/lib/python3.8/site-packages/gym/envs/registration.py", line 219, in _check_version_exists
    _check_name_exists(ns, name)
  File "/home/jz/miniconda3/envs/py38/lib/python3.8/site-packages/gym/envs/registration.py", line 197, in _check_name_exists
    raise error.NameNotFound(
gym.error.NameNotFound: Environment getout doesn't exist.

**Comment by zdx3578** [comment]
(py38) ➜  LogicRL git:(master) ✗ python3 src/play.py -s 0 -alg ppo -m getout
 -env getout  
Set all environment deterministic to seed 0
Loading
Traceback (most recent call last):
  File "src/play.py", line 141, in <module>
    main()
  File "src/play.py", line 86, in main
    model = load_model(model_file, args)
  File "src/play.py", line 23, in load_model
    model.actor.print_program()
  File "/home/jz/miniconda3/envs/py38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'MLPGetout' object has no attribute 'print_program'
(py38) ➜  LogicRL git:(master) ✗

**Comment by zdx3578** [comment]
src/train.py -s 0 -alg logic -m threefish -env threefish  -r threefish_bs_rf1    can run ok

**Comment by k4ntz** [comment]
I guess that this error is now fixed, I'm closing the issue.
